// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: snowflake/v1/services/flake_service.proto

package services

import (
	context "context"
	resources "github.com/prettykingking/snowflake/genproto/apis/snowflake/v1/resources"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FlakeServiceClient is the client API for FlakeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FlakeServiceClient interface {
	GetFlake(ctx context.Context, in *GetFlakeRequest, opts ...grpc.CallOption) (*resources.Flake, error)
}

type flakeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFlakeServiceClient(cc grpc.ClientConnInterface) FlakeServiceClient {
	return &flakeServiceClient{cc}
}

func (c *flakeServiceClient) GetFlake(ctx context.Context, in *GetFlakeRequest, opts ...grpc.CallOption) (*resources.Flake, error) {
	out := new(resources.Flake)
	err := c.cc.Invoke(ctx, "/snowflake.v1.services.FlakeService/GetFlake", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlakeServiceServer is the server API for FlakeService service.
// All implementations must embed UnimplementedFlakeServiceServer
// for forward compatibility
type FlakeServiceServer interface {
	GetFlake(context.Context, *GetFlakeRequest) (*resources.Flake, error)
	mustEmbedUnimplementedFlakeServiceServer()
}

// UnimplementedFlakeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFlakeServiceServer struct {
}

func (UnimplementedFlakeServiceServer) GetFlake(context.Context, *GetFlakeRequest) (*resources.Flake, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFlake not implemented")
}
func (UnimplementedFlakeServiceServer) mustEmbedUnimplementedFlakeServiceServer() {}

// UnsafeFlakeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlakeServiceServer will
// result in compilation errors.
type UnsafeFlakeServiceServer interface {
	mustEmbedUnimplementedFlakeServiceServer()
}

func RegisterFlakeServiceServer(s grpc.ServiceRegistrar, srv FlakeServiceServer) {
	s.RegisterService(&FlakeService_ServiceDesc, srv)
}

func _FlakeService_GetFlake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFlakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlakeServiceServer).GetFlake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/snowflake.v1.services.FlakeService/GetFlake",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlakeServiceServer).GetFlake(ctx, req.(*GetFlakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FlakeService_ServiceDesc is the grpc.ServiceDesc for FlakeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FlakeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "snowflake.v1.services.FlakeService",
	HandlerType: (*FlakeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFlake",
			Handler:    _FlakeService_GetFlake_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "snowflake/v1/services/flake_service.proto",
}
